language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - py.test --cov-report term-missing --cov taran
after_success:
  coveralls
