services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: taran
      POSTGRES_USER: taran
      POSTGRES_PASSWORD: taran
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
