"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import type { Digest } from "@/types/api";
import { formatShortDate } from "@/lib/utils";

interface DownloadPdfButtonProps {
  digest: Digest;
}

export function DownloadPdfButton({ digest }: DownloadPdfButtonProps) {
  const [loading, setLoading] = useState(false);

  async function handleDownload() {
    setLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let y = 20;

      const checkPage = (needed: number) => {
        if (y + needed > doc.internal.pageSize.getHeight() - 20) {
          doc.addPage();
          y = 20;
        }
      };

      // Header
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("MAILBRIEF", margin, y);
      const dateRange = `${formatShortDate(digest.PeriodStart)} – ${formatShortDate(digest.PeriodEnd)}`;
      doc.text(dateRange, pageWidth - margin, y, { align: "right" });
      y += 10;

      // Title
      doc.setFontSize(18);
      doc.setTextColor(0);
      const titleLines = doc.splitTextToSize(digest.Title, contentWidth);
      checkPage(titleLines.length * 8);
      doc.text(titleLines, margin, y);
      y += titleLines.length * 8 + 2;

      // Email count
      doc.setFontSize(10);
      doc.setTextColor(120);
      doc.text(`${digest.EmailCount} emails`, margin, y);
      y += 10;

      // Summary
      if (digest.Summary) {
        doc.setFontSize(11);
        doc.setTextColor(0);
        const summaryLines = doc.splitTextToSize(digest.Summary, contentWidth);
        checkPage(summaryLines.length * 5 + 5);
        doc.text(summaryLines, margin, y);
        y += summaryLines.length * 5 + 8;
      }

      // Highlights
      if (digest.Highlights?.length > 0) {
        checkPage(15);
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text("Highlights", margin, y);
        y += 7;

        doc.setFontSize(10);
        doc.setTextColor(60);
        for (const highlight of digest.Highlights) {
          const lines = doc.splitTextToSize(`• ${highlight}`, contentWidth - 4);
          checkPage(lines.length * 5 + 2);
          doc.text(lines, margin + 2, y);
          y += lines.length * 5 + 2;
        }
        y += 5;
      }

      // Top Topics
      if (digest.TopTopics?.length > 0) {
        checkPage(15);
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text("Top Topics", margin, y);
        y += 7;

        doc.setFontSize(10);
        doc.setTextColor(60);
        doc.text(digest.TopTopics.join("  •  "), margin + 2, y);
        y += 10;
      }

      // Included Emails
      if (digest.Items?.length > 0) {
        checkPage(15);
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text("Included Emails", margin, y);
        y += 8;

        for (const item of digest.Items) {
          checkPage(20);

          // Subject
          doc.setFontSize(10);
          doc.setTextColor(0);
          const subjectLines = doc.splitTextToSize(
            item.Subject || `Email ${item.SortOrder + 1}`,
            contentWidth - 4,
          );
          doc.text(subjectLines, margin + 2, y);
          y += subjectLines.length * 4.5;

          // Sender
          if (item.FromName) {
            doc.setFontSize(9);
            doc.setTextColor(120);
            doc.text(item.FromName, margin + 2, y);
            y += 4;
          }

          // Summary
          if (item.Summary) {
            doc.setFontSize(9);
            doc.setTextColor(80);
            const itemSummary = doc.splitTextToSize(item.Summary, contentWidth - 4);
            checkPage(itemSummary.length * 4);
            doc.text(itemSummary, margin + 2, y);
            y += itemSummary.length * 4;
          }

          y += 5;
        }
      }

      // Footer
      checkPage(15);
      y += 5;
      doc.setDrawColor(220);
      doc.line(margin, y, pageWidth - margin, y);
      y += 5;
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Generated by MailBrief", margin, y);

      // Download
      const filename = `${digest.Title.replace(/[^a-zA-Z0-9-_ ]/g, "").slice(0, 50).trim()}.pdf`;
      doc.save(filename);
      toast.success("PDF downloaded");
    } catch {
      toast.error("Failed to generate PDF");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={handleDownload} disabled={loading}>
      {loading ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Download className="size-4 mr-1.5" />}
      PDF
    </Button>
  );
}
